### ISSUE TITLE
double jumping

### ISSUE THREAD

**Issue by gDiode** [HouraiTeahouse/GensoShojokosen#20]
it's really inconsistent:
if you spam the jump key it will create a huge jump
but if you wait the jump the second will almost do nothing or just slow down the character.
how to solve this?
each time the player uses a double jump you could reset the y acceleration so this doesn't occur
here's a video showing the bug:
https://youtu.be/djn0wGx8q5c

**Comment by james7132** [comment]
The jumping currently works by adding a relative amount to upward momentum. This should be easily fixed in an upcoming commit.
