### ISSUE TITLE
Open Mailbox is not open without invitation

### ISSUE THREAD

**Issue by Shredster7** [HouraiTeahouse/GensoShojokosen#9]
This is technically not an issue with the game itself, and I'd like to apologize if this is not the correct place to discuss this type of issue.

It appears that the Dropbox folder "Open Mailbox" is not actually open to users who have not received an email invitation to upload files to the Dropbox. This is a limitation of Dropbox itself as it is meant to be used as a mass downloading service, not a mass uploading service. 

That being said, there are workarounds or alternatives that would allow for a public upload for non-code files. The most common recommendation (when entering variations of "public upload" into Google, at least) seems to be a web-based application called "DB Inbox".

I tried it for myself just to see how it works. it's basically a one-way upload that deposits the uploaded files into an app-created subfolder. The uploader cannot delete their uploads or other people's uploads. However, it does not appear to possess any kind of antivirus scanner - it would be wise to configure the host Dropbox accounts to not synchronize the inbox folder with the host computers.

However, there are still other methods that could theoretically be used to achieve the same ends.

**Comment by james7132** [comment]
This is definitely something to consider. I'll keep an eye out for potential solutions. I may just put up an email address to mail assets to, and put a script to dump approved emails to dropbox instead.

**Comment by james7132** [comment]
OK, as a better solution. Simply email teahouse.hourai@gmail.com the asset,  using a file hosting service as necessary. I will manually put the assets in as needed.
